# Generated by Django 3.1.12 on 2023-03-26 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weddingbooking',
            name='customer',
        ),
        migrations.AddField(
            model_name='weddingbooking',
            name='email',
            field=models.EmailField(default='abc', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weddingbooking',
            name='name',
            field=models.CharField(default='abc', max_length=122),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weddingbooking',
            name='phone',
            field=models.CharField(default='abc', max_length=20),
            preserve_default=False,
        ),
    ]
