# Generated by Django 4.1.7 on 2023-03-25 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingApp', '0002_contactform_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Station Phone Number')),
                ('emergency_center', models.CharField(blank=True, max_length=255, null=True, verbose_name='Emergency Center Phone Number')),
                ('help_desk', models.CharField(blank=True, max_length=255, null=True, verbose_name='Help Desk Phone Number')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
