# Generated by Django 4.1.7 on 2023-03-26 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingApp', '0003_alter_contactform_id_alter_contactnumber_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weddingbooking',
            name='date_booked',
            field=models.DateField(),
        ),
    ]
