# Generated by Django 4.1.7 on 2023-03-26 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingApp', '0005_remove_weddingbooking_customer_weddingbooking_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Customer', 'verbose_name_plural': 'Customers'},
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='email',
            new_name='email_id',
        ),
        migrations.AlterField(
            model_name='service',
            name='service_type',
            field=models.CharField(choices=[('photo', 'Photography'), ('video', 'Videography'), ('decor', 'Decoration'), ('catering', 'Catering'), ('music', 'Music DJ'), ('makeup', 'Makeup'), ('wedding_planner', 'Wedding Planner'), ('resort', 'Resort')], max_length=20),
        ),
    ]
